<font size=6><b>Lec11. Ta-Lib

ref : https://mrjbq7.github.io/ta-lib/<br>
**Function List**
<pre>
Overlap Studies
Momentum Indicators
Volume Indicators
Volatility Indicators
Price Transform
Cycle Indicators
Pattern Recognition
Statistic Functions
Math Transform
Math Operators


In [37]:
import talib.abstract as ta
from pandas_datareader import data
from talib import MA_Type
import numpy as np

In [23]:
df = data.DataReader('215600.KQ','yahoo', '2017-01-01', '2018-01-31')\
    .dropna(how='all')\
    .rename(columns=lambda col:col.lower()) # 컬럼 이름을 소문자로 변경
df.head()

high      low     open    close    volume  adj close
Date                                                               
2017-01-02  13250.0  12900.0  13250.0  12950.0  497396.0    12950.0
2017-01-13  12350.0  11850.0  12200.0  12100.0  612247.0    12100.0
2017-01-17  11600.0  11250.0  11500.0  11450.0  748532.0    11450.0
2017-01-23  11150.0  10400.0  11100.0  10500.0  914339.0    10500.0
2017-02-07  10700.0  10300.0  10450.0  10600.0  365127.0    10600.0

## 이동평균 

In [18]:
%timeit ta.MA(df, timeperiod=5)
ta.MA(df, timeperiod=5).head()

71.3 µs ± 2.26 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Date
2017-01-02        NaN
2017-01-13        NaN
2017-01-17        NaN
2017-01-23        NaN
2017-02-07    11520.0
dtype: float64

In [14]:
%timeit df['close'].rolling(window=5).mean()
df['close'].rolling(window=5).mean().tail() 

179 µs ± 1.93 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Date
2018-01-25    108820.0
2018-01-26    110220.0
2018-01-29    111400.0
2018-01-30    110420.0
2018-01-31    109500.0
Name: close, dtype: float64

## 단순이동평균(SMA)

In [21]:
ta.SMA(df).tail()

Date
2018-01-25    95876.666667
2018-01-26    96553.333333
2018-01-29    97286.666667
2018-01-30    97986.666667
2018-01-31    98686.666667
dtype: float64

In [31]:
ta.EMA(df).tail()

Date
2018-01-25     99539.795872
2018-01-26    100214.647752
2018-01-29    100845.960800
2018-01-30    101442.995587
2018-01-31    101730.544259
dtype: float64

In [32]:
ta.WMA(df).tail()

Date
2018-01-25    100753.548387
2018-01-26    101664.731183
2018-01-29    102532.258065
2018-01-30    103358.924731
2018-01-31    103869.462366
dtype: float64

## MACD(Moving Average Convergence/Divergence)

In [47]:
macd, macdsignal, macdhist = ta.MACD(df['close'], fastperiod=12, slowperiod=26, signalperiod=9)
print(macd[-3:], macdsignal[-3:], macdhist[-3:])

[4838.79595364 4739.15600131 4272.04030075] [4233.05922422 4334.27857964 4321.83092386] [605.73672942 404.87742167 -49.79062311]


In [26]:
# help('ta.SMA')

No Python documentation found for 'ta.SMA'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [45]:
close_arr = np.asarray(df["close"])
high_arr  = np.asarray(df["high"])
low_arr   = np.asarray(df["low"])

## BBAND

In [44]:
#볼린저 계산
upper, middle, low = ta._ta_lib.BBANDS(close_arr, 20, 2, 2, matype=MA_Type.SMA)
print(upper[-3:])
print(middle[-3:])
print(low[-3:] )

[115769.29211622 116437.62635222 116591.26932199]
[103815. 104195. 104340.]
[91860.70788378 91952.37364778 92088.73067801]


## 기타

In [ ]:
ta._ta_lib.RSI(close_arr, 14)
ta._ta_lib.CCI(high_arr, low_arr, close_arr, 14)
ta._ta_lib.WILLR(high_arr, low_arr, close_arr, 14)
ta._ta_lib.VAR(close_arr, 5, 1)
ta._ta_lib.ADX(high_arr, low_arr, close_arr, 14)
ta._ta_lib.PLUS_DI(high_arr, low_arr, close_arr, 14)
ta._ta_lib.PLUS_DM(high_arr, low_arr, 14)
ta._ta_lib.ATR(high_arr, low_arr, close_arr, 30)