# lec04_reshape

In [1]:
import numpy as np
import pandas as pd

# 데이터 구조 (유형)
<pre>
* Scalar   : 단일 값
* Vector   : 숫자 열(array-like)
* Matrix   : 행렬, 벡터 묶음
* Tensor   : 메트릭스 묶음

<img src ="https://mblogthumb-phinf.pstatic.net/MjAyMDA1MjVfMjMx/MDAxNTkwMzY0MTI4NTE1.f-y_r75ikUM3Mr406dl5ILpLArs8vtef5jOb1_bncZcg.t1-XQSmZiTGDdV2o2JS3LpCb2rb3rsRGCWgvmOuvYYYg.PNG.nabilera1/image.png?type=w800">

# List VS Array VS Series

In [2]:
num_list = [1,2,3,4]
print(len(num_list), num_list, np.ndim(num_list))

num_arr = np.array(num_list)
print(len(num_arr), num_arr.shape, num_arr, np.ndim(num_list))
      
s = pd.Series(num_arr) 
print(len(s) , s.shape, s.values.shape, np.ndim(num_list))
print(s.values)
print(s)

4 [1, 2, 3, 4] 1
4 (4,) [1 2 3 4] 1
4 (4,) (4,) 1
[1 2 3 4]
0    1
1    2
2    3
3    4
dtype: int32


In [3]:
num_list = [1,2,3,4]
print(len(num_list), num_list)
#np.ndim() >> 차수 출력

num_arr = np.array(num_list) # 가로줄
print(num_arr.shape, num_arr)

S = pd.Series(num_arr) # 세로줄
print(S, S.values, len(S), S.shape,  S.values.shape) 

4 [1, 2, 3, 4]
(4,) [1 2 3 4]
0    1
1    2
2    3
3    4
dtype: int32 [1 2 3 4] 4 (4,) (4,)


# 요소 접근

In [4]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(2,3,4)
print(re_arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
print(   len(re_arr), len(re_arr[0]), len(re_arr[0][0])   )

2 3 4


# arange() VS range()
(시작,끝,간격)

In [6]:
a = np.arange(4,12,2)
a

array([ 4,  6,  8, 10])

In [7]:
a = range(4,12,2)
print(type(a))
list(a)

<class 'range'>


[4, 6, 8, 10]

In [8]:
for i in [1,2,3]:
    print(i)

1
2
3


In [9]:
for i in np.array([1,2,3]):
    print(i)

1
2
3


In [10]:
for i in range(1,4):        #[1,2,3]
    print(i)

1
2
3


In [11]:
for i in np.arange(1,4):   #[123] >> array
    print(i)

1
2
3


# np.zeros() VS np.ones() VS np.likes()

## np.zeros()
* 0을 원하는 갯수, 형식으로 만든다

In [12]:
np.zeros(5, dtype = int)
# default는 float

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((5,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## np.ones()
* 1을 원하는 갯수, 형식으로 만든다

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

## np.like()
* np.zeros_like(), np.ones_like(), np.empty_like(), np.full_like()

In [15]:
sample = np.zeros((5,3), dtype = int)
print(sample, sample.shape)
temp = np.ones_like(sample)
print(temp, temp.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]] (5, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]] (5, 3)


# 차수(Dimension)

<img src = "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcSoMOs%2Fbtqt0a2Dc2y%2FQhkfwhiWqeUKvNfsM2H29K%2Fimg.png">

## 1D
* axis = 0

In [16]:
num_list = [1,2,3,4]
print(np.ndim(num_list))

1


## 2D
* 행 axis = 0
* 열 axis = 1

In [17]:
num_list = [  [1,2,3],[2],[3],[4] ]
num_arr = np.array(num_list)
# print(num_arr.shape, num_arr)
# 차수  >>>>  대괄호 갯수!!!
print(np.ndim(num_list), np.array(num_list).shape)
# 가변행렬 >> 1차로 인식한다

1 (4,)


C:\Users\ASIA\AppData\Local\Temp\ipykernel_7692\2142790882.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  num_arr = np.array(num_list)
C:\AI\pythonProject\venv\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)
C:\Users\ASIA\AppData\Local\Temp\ipykernel_7692\2142790882.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If y

In [18]:
num_list = [  [1,2,3],[2,2,2],[3,3,3],[4,4,4] ]
print(np.ndim(num_list), np.array(num_list).shape)

2 (4, 3)


## 3D
* (2,3,4) > 3행 4열 2depth
* 행 axis = 0
* 열 axis = 1
* 폭 axis = 2

In [19]:
num_arr = np.arange(0,24)
print(num_arr.shape, '\n',num_arr)
print()
re_arr = num_arr.reshape(6,4)
print(re_arr.shape,'\n',re_arr)
print()

re_arr = num_arr.reshape(2,3,4)
print(re_arr.shape, '\n', re_arr)

# num_list = [[  [1] ]]
# print(np.ndim(num_list), np.array(num_list).shape)

(24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

(6, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

(2, 3, 4) 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


600 *( 28 * 28)  >> depth * (row * col)
600장 >> frame 600 >> depth 600 >> tensor 600  //// axis = 2

# 축(axis)

* axis = none (default) >> sum all of the elements

In [20]:
num_arr = np.arange(0,24)
print(np.sum(num_arr)) # >> 축이 없다면 요소 값들의 합

276


In [21]:
num_arr = num_arr.reshape(6,4)
print(num_arr)
print()
print(np.sum(num_arr, axis = 0))  # ↓ 행기준
print(np.sum(num_arr, axis = 1))  # → 열기준

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[60 66 72 78]
[ 6 22 38 54 70 86]


In [22]:
num_arr = num_arr.reshape(2,3,4)
print(num_arr)
print()
print()

print(np.sum(num_arr, axis = 0))   # 폭 방향    axis = 0, 0번째 기준(2)으로  >>>  3*4
print()

print(np.sum(num_arr, axis = 1))   # ↓          axis = 1, 1번째 기준(3)으로  >>>  2*4
print()

print(np.sum(num_arr, axis = 2))   # →          axis = 2, 2번째 기준(4)으로  >>>  2*3

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[12 15 18 21]
 [48 51 54 57]]

[[ 6 22 38]
 [54 70 86]]


# reshape
<pre>
* reshape(n, -1) : 열은 알아서 
* reshape(-1)    : 1차로 만들기
* .ravel()       : 1차로 만들기
* .flatten()     : 1차로 만들기

In [23]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(6,-1) # 6줄, 칸은 알아서
print(re_arr)

aa = re_arr.reshape(-1,)       # 1차로 만들기

print()
print(aa)

bb = re_arr.ravel()           # 1차로 만들기
print()
print(bb)

cc = re_arr.flatten()         # 1차로 만들기
print()
print(cc)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## reshape() VS resize()
* reshape() : 변형한 행열을 반환
* resize()  : 원본자체를 변형, 반환값 없다

In [34]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(6,-1) 

print(num_arr)
print(re_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [36]:
num_arr = np.arange(0,24)
num_arr.resize(6,4) # >> 원본 자체를 바꾼다, return이 없다 

print(num_arr)
print(re_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## 차원확대
* reshape()
* 슬라이싱[ np.newaxis()  or none ]
* expand_dims(a, axis)


### reshape

In [40]:
num_arr = np.arange(0,24)
print(num_arr.ndim,"\n", num_arr)

res = num_arr.reshape(1,24)
print(res.ndim,res.shape,"\n", res)

res = num_arr.reshape(24,1)
print(res.ndim,res.shape,"\n", res)

1 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2 (1, 24) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
2 (24, 1) 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### 슬라이싱

In [45]:
num_arr = np.arange(0,24)
res = num_arr[np.newaxis, : ]
res = num_arr[None, : ]

print(res)
res = num_arr[ :, np.newaxis ]
res = num_arr[ :, None ]
print(res)


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### expand_dims()

In [47]:
num_arr = np.arange(0,24)
res = np.expand_dims(num_arr, axis=0)
print(res)
res = np.expand_dims(num_arr, axis=1)
print(res)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


## 차원축소
* 1차원 : reshape(-1), ravel(), flatten()
* slicing ":"
    - .....
* np.squeeze(axis = None) : 차원 1은 모두 없앤다

In [49]:
num_arr = np.arange(0,24)
res = np.expand_dims(num_arr, axis=1)
print(res.ndim, res.shape, res)
 

2 (24, 1) [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [ ]:
res = np.expand_dims(num_arr, axis=1)
print(res)

### np.squeeze(axis = None)

In [51]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(1,24,1)
print(re_arr.ndim, re_arr.shape, re_arr)


num_arr = np.arange(0,24)
re_arr = num_arr.reshape(1,6,4,1)
print(re_arr.ndim, re_arr.shape, re_arr)

3 (1, 24, 1) [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]]]


# Stack ( ==concatenate )
* hstack()
* vstack()
* column_stack()
* <img src = "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F9909EF345D53F4D916">

## hstack()

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(   np.hstack((a,b))   )
print()
print(   np.concatenate((a,b), axis = 0)   )



[1 2 3 4 5 6]

[1 2 3 4 5 6]


## vstack()

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(   np.vstack((a,b))   )
print()
print(   np.concatenate([[a,b]], axis = 1)   )

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]


## column_stack()

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])


print(   np.column_stack((a,b))   )

[[1 4]
 [2 5]
 [3 6]]


## stack()

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(  np.stack((a,b), axis = 0)  )
print()
print(  np.stack((a,b), axis = 1)  )

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


# broadcasting
* array 객체!!!
<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

## list

In [28]:
num_list = [1,2,3]
# print(num_list+1)
# can only concatenate list (not "int") to list

TypeError: can only concatenate list (not "int") to list

In [29]:
print(num_list*2)

[1, 2, 3, 1, 2, 3]


In [30]:
num_list = [1,2,3]
arr = [4,4,4]
num_list.append(arr)
print(num_list)
num_list.extend(arr)
print(num_list)


[1, 2, 3, [4, 4, 4]]
[1, 2, 3, [4, 4, 4], 4, 4, 4]


## array

In [31]:
num_arr = np.array([1,2,3])
num_arr =  num_arr * 3
print(num_arr)

[3 6 9]


In [32]:
num_arr = np.array([1,2,3])
num_arr =  num_arr +1
print(num_arr)

[2 3 4]


# 차원변경
* reshape() resize()