<font size=6><b> Lec04. reshape
<pre>
* 데이터 구조(유형)
    * 스칼라(scalar) : 한개의 숫자
    * 벡터(vector)   : 여러개 숫자 묶음 array-like
    * 행렬(matrix)   : 벡터의 묶음
    * 텐서(tensor)   : 행렬의 묶음

<img src="https://mblogthumb-phinf.pstatic.net/MjAyMDA1MjVfMjMx/MDAxNTkwMzY0MTI4NTE1.f-y_r75ikUM3Mr406dl5ILpLArs8vtef5jOb1_bncZcg.t1-XQSmZiTGDdV2o2JS3LpCb2rb3rsRGCWgvmOuvYYYg.PNG.nabilera1/image.png?type=w800" width=500>

In [1]:
import numpy as np
import pandas as pd

# list array Series

In [2]:
num_list = [1,2,3,4]
print(len(num_list), num_list, np.ndim(num_list))

num_arr = np.array(num_list)
print(len(num_arr), num_arr.shape, num_arr, np.ndim(num_list))
      
s = pd.Series(num_arr) 
print(len(s) , s.shape, s.values.shape, np.ndim(num_list))
print(s.values)
print(s)

4 [1, 2, 3, 4] 1
4 (4,) [1 2 3 4] 1
4 (4,) (4,) 1
[1 2 3 4]
0    1
1    2
2    3
3    4
dtype: int32


## 요소 접근

## 2D

In [3]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(6,4)
print(re_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
len(re_arr) , re_arr

(6,
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [5]:
len(re_arr[0]) , re_arr[0]

(4, array([0, 1, 2, 3]))

## 3D

In [6]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(2,3,4)
print(re_arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
len(re_arr) , re_arr

(2,
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

In [8]:
len(re_arr[0]) , re_arr[0]

(3,
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [9]:
len(re_arr[0][0]) , re_arr[0][0]

(4, array([0, 1, 2, 3]))

In [10]:
# len(re_arr[0][0][0]) 
re_arr[0][0][0]

0

# arange() vs lange()
<pre>
* arange(s, e, inc) vs lange(s, e, inc)
* array             vs range 객체
* 요소값출력         vs list(a)로 감싸서 요소값 출력
* for i in range(10) : 


In [11]:
a = np.arange(4, 12, 2)
a

array([ 4,  6,  8, 10])

In [12]:
a = range(4,12,2)
print(type(a))
list( a )

<class 'range'>


[4, 6, 8, 10]

In [13]:
for i in [1,2,3] :
    print(i)

1
2
3


In [14]:
for i in np.array([1,2,3]) :
    print(i)

1
2
3


In [15]:
for i in range(1,4) :    #[0,1,2]
    print(i)

1
2
3


In [16]:
# for i in list(range(1,4)) :    #[0,1,2]
#     print(i)

In [17]:
# for i in np.array(list(range(1,4))) :    #range --> [0,1,2] --> [0 1 2]
#     print(i)

In [18]:
for i in np.arange(1,4) : #[0 1 2]
    print(i)

1
2
3


In [19]:
for i in range(3) :
    print(i)

0
1
2


In [20]:
for i in np.arange(3) :  #[0 1 2]
    print(i)

0
1
2


# np.zeros() ones() _like()

In [21]:
np.zeros((5), dtype=int)

array([0, 0, 0, 0, 0])

In [22]:
np.zeros((5,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones((5), dtype=int)

array([1, 1, 1, 1, 1])

In [24]:
sample = np.zeros((5,3), dtype=int)
print(sample.shape, sample)

temp = np.ones_like(sample)
print(sample.shape, temp)

(5, 3) [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(5, 3) [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


# 차수(Demention)

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcSoMOs%2Fbtqt0a2Dc2y%2FQhkfwhiWqeUKvNfsM2H29K%2Fimg.png" width=400>

## 1D  [ ... ]
* <font color=red><b>axis=0 (가로)

In [25]:
num_list = [1,2,3,4]
print(np.ndim(num_list))

1


## 2D [[ ... ]]
* <font color=red><b>axis=0 (세로 ↓)
* <font color=red><b>axis=1 (가로 →)

* 가변 행렬의 경우 list[요소]를 하나의 값으로 인식

In [26]:
# num_list = [  [1,2,3],[2],[3],[4] ]
# num_arr = np.array(num_list)
# print(num_arr.shape, num_arr)
# print(np.ndim(num_list))  

In [27]:
num_list = [  [1,2,3],[2,2,2],[3,2,2],[4,2,2] ]
print(np.ndim(num_list))

2


## 3D [[[ ... ]]]
* (2,3,4) : 3행4열  2덩어리
* <font color=red><b>axis=0 (세로 ↓)
* <font color=red><b>axis=1 (가로 →)
* <font color=red><b>axis=2 (폭)

In [28]:
num_arr = np.arange(0,24)
print(num_arr.shape, "\n", num_arr)
print()

re_arr = num_arr.reshape(6,4)
print(re_arr.shape, "\n", re_arr)
print()


re_arr = num_arr.reshape(2,3,4)
print(re_arr.shape, "\n", re_arr)
print()



(24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

(6, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

(2, 3, 4) 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



# 축(axis)

## axis=None
*  axis=None : sum all of the elements

In [29]:
num_arr = np.arange(0,24)
print(num_arr)
np.sum(num_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


276

In [30]:
num_arr = np.arange(0,24)
num_arr = num_arr.reshape(6,4) #6줄4칸
print(num_arr)
np.sum(num_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


276

## 2D axis=0
* 행 총합
* <font color=red><b>axis=0 (행)
* <font color=red><b>axis=1 (열)

In [31]:
num_arr = np.arange(0,24)
num_arr = num_arr.reshape(6,4) #6줄4칸
print(num_arr)
np.sum(num_arr, axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([60, 66, 72, 78])

## 2D axis=1
* 열 총합
* <font color=red><b>axis=0 (행)
* <font color=red><b>axis=1 (열)

In [32]:
num_arr = np.arange(0,24)
num_arr = num_arr.reshape(6,4) #6줄4칸
print(num_arr)
np.sum(num_arr, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([ 6, 22, 38, 54, 70, 86])

## 3D 
* (덩어리, 줄, 칸)
<pre>
<font color=red><b>axis=0 : (_____ 줄,칸)
<font color=red><b>axis=1 : (덩어리,__,칸)
<font color=red><b>axis=2 : (덩어리,줄,__)

In [33]:
num_arr = np.arange(0,24)
num_arr = num_arr.reshape(2,3,4) # (3줄4칸 ) 2덩어리
print(num_arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [34]:
np.sum(num_arr, axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [35]:
np.sum(num_arr, axis=1) 

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [36]:
np.sum(num_arr, axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

# reshape()
* reshape(행,열) : (행, -1) : 알아서 계산

## reshape() vs. resize()
* reshape() : 원본은 두고 변환한 행열을 반환
* resize() : 원본을 변환, 리턴없음

In [37]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(6,4) #6줄4칸

print(num_arr)
print(re_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [38]:
num_arr = np.arange(0,24)
num_arr.resize(6,4) #6줄4칸
print(num_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## 차원 확대 
* reshape(1, -1, ...)
* <font color=red><b>슬라이싱 [: , np.newaxis or None] 
    * 확장하고 싶은 축에 np.newaxis or None 입력
* <font color=red><b> np.expand_dims(a, axis)

In [39]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape, "\n", num_arr)  # 가로줄 []

res = num_arr.reshape(1, 24)         # 가로줄 [ [0,1..23] ]
print(res.ndim,  res.shape, "\n" , res)

res = num_arr.reshape(1, -1)         # 가로줄 [ [0,1..23] ]
print(res.ndim, res.shape, "\n" , res)

res = num_arr.reshape(24, 1)         # 세로줄 [ [0],[1]..[23] ]
print(res.ndim,  res.shape, "\n" , res)

res = num_arr.reshape(-1, 1)         # 세로줄 [ [0],[1]..[23] ]
print(res.ndim,  res.shape, "\n" , res)

1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2 (1, 24) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
2 (1, 24) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
2 (24, 1) 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
2 (24, 1) 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [40]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape, "\n", num_arr)  # 가로줄 []

res = num_arr[np.newaxis, :]
print(res.ndim, res.shape, "\n", res)  # 가로줄 []

res = num_arr[None, :]
print(res.ndim, res.shape, "\n", res)  # 가로줄 []


res = num_arr[:, np.newaxis]
print(res.ndim, res.shape, "\n", res)  # 세로줄 []


res = num_arr[:, None]
print(res.ndim, res.shape, "\n", res)  # 세로줄 []

1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2 (1, 24) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
2 (1, 24) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
2 (24, 1) 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
2 (24, 1) 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [41]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape, "\n", num_arr)  # 가로줄 []

res = np.expand_dims(num_arr, axis=0)
print(res.ndim, res.shape, "\n", res)  # 가로줄 []

res = np.expand_dims(num_arr, axis=1)
print(res.ndim, res.shape, "\n", res)  # 세로줄 []

res = np.expand_dims(num_arr, axis=(0,1))
print(res.ndim, res.shape, "\n", res)  # 세로줄 []

res = np.expand_dims(num_arr, axis=(0,2))
print(res.ndim, res.shape, "\n", res)  # 세로줄 []

1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2 (1, 24) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
2 (24, 1) 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
3 (1, 1, 24) 
 [[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23]]]
3 (1, 24, 1) 
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]]]


## 차원 축소
* 1차원  <font color=red><b>reshpae(-1) == ravel() == flatten()     
* <font color=red><b>res = re_arr[1, ...]    
* 슬라이싱   :  ...    
* np.squeeze(a, axis=None) : 차수1은 모두 지운다

In [42]:
num_arr = np.arange(0,24)
print(num_arr)
# re_arr = num_arr.reshape(6,4) #6줄4칸
re_arr = num_arr.reshape(2,3,-1) #6줄 , 칸은 알아서 계산
print(re_arr)

aa = re_arr.reshape(-1) 
print(aa)

bb = re_arr.ravel() 
print(bb)

cc = re_arr.flatten()
print(cc)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [43]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape, "\n", num_arr)  # 가로줄 []

re_arr = num_arr.reshape(6,4)
print(re_arr.ndim, re_arr.shape, "\n", re_arr) 

res = re_arr[1, :]
print(res.ndim, res.shape, "\n", res)  #

res = re_arr[:, 2]
print(res.ndim, res.shape, "\n", res)  #

res = re_arr[:, -1]
print(res.ndim, res.shape, "\n", res)  #

1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2 (6, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
1 (4,) 
 [4 5 6 7]
1 (6,) 
 [ 2  6 10 14 18 22]
1 (6,) 
 [ 3  7 11 15 19 23]


In [44]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape, "\n", num_arr)  # 가로줄 []

re_arr = num_arr.reshape(2,3,4)
print(re_arr.ndim, re_arr.shape, "\n", re_arr) 

res = re_arr[1, :]
print(res.ndim, res.shape, "\n", res)  #

res = re_arr[1, ...]
print(res.ndim, res.shape, "\n", res)  #


1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3 (2, 3, 4) 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
2 (3, 4) 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2 (3, 4) 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [45]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape, "\n", num_arr)  # 가로줄 []

re_arr = num_arr.reshape(1,6,1,4,1)
print(re_arr.ndim, re_arr.shape, "\n", re_arr) 

res = np.squeeze(re_arr) #, axis=None)
print(res.ndim, res.shape, "\n", res)  #

1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
5 (1, 6, 1, 4, 1) 
 [[[[[ 0]
    [ 1]
    [ 2]
    [ 3]]]


  [[[ 4]
    [ 5]
    [ 6]
    [ 7]]]


  [[[ 8]
    [ 9]
    [10]
    [11]]]


  [[[12]
    [13]
    [14]
    [15]]]


  [[[16]
    [17]
    [18]
    [19]]]


  [[[20]
    [21]
    [22]
    [23]]]]]
2 (6, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# Stack == concatenate()
* hstack()
* vstack()
* column_stack()
* ref : https://rfriend.tistory.com/352

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F9909EF345D53F4D916">

## hstack()

In [46]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(  np.hstack([a, b])  )   #----------------------추천
print(  np.concatenate([a, b] , axis=0)   )

[ 1  2  3 10 20 30]
[ 1  2  3 10 20 30]


## vstack()

In [47]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(  np.vstack([a, b])  )  #----------------------추천
print(  np.concatenate([[a, b]] , axis=1)  ) 

[[ 1  2  3]
 [10 20 30]]
[[ 1  2  3]
 [10 20 30]]


## colume_stack()

In [48]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(  np.column_stack([a, b])  )   #----------------------추천
# print(  np.stack([a, b], axis=1)   )

[[ 1 10]
 [ 2 20]
 [ 3 30]]


## stack()
* axis=0  : 가로합치기
    * pd.concat([df1, df2], axis=0)
* axis=1  : 세로합치기 (s + s)
    * pd.concat([df1, df2], axis=1)

In [49]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(  np.stack([a, b], axis=0)   )  

[[ 1  2  3]
 [10 20 30]]


In [50]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(  np.stack([a, b], axis=1)   )  

[[ 1 10]
 [ 2 20]
 [ 3 30]]


# BroadCasting

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width=400>

## list
* 곱하기 : 확장 extend()
* 더하기 : 에러

In [51]:
num_list = [1,2,3] 
# num_list = num_list + 3  #에러
num_list = num_list * 3  #3번반복
print(num_list)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [52]:
num_list = [1,2,3] 
arr = [1,2,3]
num_list.append(arr) 
print( num_list)

[1, 2, 3, [1, 2, 3]]


In [53]:
num_list = [1,2,3] 
arr = [1,2,3]
num_list.extend(arr) 
print( num_list)

[1, 2, 3, 1, 2, 3]


## array
* 곱하기 / 더하기 : 연산

In [54]:
num_arr = np.array([1,2,3] )
num_arr = num_arr * 3  # list:확장  arr:연산(곱하기)
print(num_arr)

[3 6 9]


In [55]:
num_arr = np.array([1,2,3] )
num_arr = num_arr + 3  # list:에러  arr:연산(더하기)
print(num_arr)

[4 5 6]
